apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
  namespace: deploy-hml
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-pod
        image: gcr.io/bdr-jenkins/helloword:0.1
        ports: 
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: deploy-hml
spec:
  selector:
    app: hello-world
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
